name: Update Docker Hub README

on:
  push:
    branches:
      - main
    paths:
      - "README.md"

jobs:
  update-readme:
    name: Update Docker Hub README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Update Docker Hub README
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
          readme-filepath: ./README.md
